name: Backend Deploy

on:
  push:
    branches:
      - taskfeatures

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Restart backend server
        run: |
          pm2 restart all || pm2 start src/server.js --name backend